### ISSUE TITLE
Deleting Character

### ISSUE THREAD

**Issue by ProjectRogueRP** [thelindat/esx_multicharacter#1]
I go to delete a test character we made while testing the multicharacter. And it doesnt seem to delete the character out of the DB. The DB does to register all characters as Char1:license and so on. There is no errors in the F8 Console or Main Console.

**Comment by thelindat** [comment]
Have you set your database name in the server file?

**Comment by ProjectRogueRP** [comment]
Hey @thelindat I did what you suggested and got it taken care of! Thank you. Now I am getting this notification in the Server Console. Any ideas?

![image](https://user-images.githubusercontent.com/83529694/120312996-0dad9380-c29f-11eb-8d15-883bcb185722.png)

**Comment by thelindat** [comment]
https://brouznouf.github.io/fivem-mysql-async/queries/

It's just storing the query in advance.
