### ISSUE TITLE
Gettiing a issue with the Multi-Character

### ISSUE THREAD

**Issue by CoreVF** [thelindat/esx_multicharacter#13]
![image](https://user-images.githubusercontent.com/78930425/122284622-a00a8580-cea2-11eb-8108-2175d66b1c9a.png)

**Comment by thelindat** [comment]
Try the latest commit.

**Comment by xxliljaexx** [comment]
ight added it in and stuck here io get this error
![image](https://user-images.githubusercontent.com/78002427/122837551-464ef480-d2c2-11eb-8053-304324472325.png)
EDIT: two more errors also i am using esx v1 final
![image](https://user-images.githubusercontent.com/78002427/122837576-51098980-d2c2-11eb-9447-4f4ec1e6d187.png)
![image](https://user-images.githubusercontent.com/78002427/122837590-55ce3d80-d2c2-11eb-89fa-a1d1c89c3dcd.png)
