### ISSUE TITLE
Character not loading

### ISSUE THREAD

**Issue by VojtaNN** [thelindat/esx_multicharacter#16]
I have these errors after installing your multicharacter.
![Výstřižek](https://user-images.githubusercontent.com/61760213/122747206-15070200-d28b-11eb-99be-86f71a4bd974.PNG)
![Výstřižek1](https://user-images.githubusercontent.com/61760213/122747210-159f9880-d28b-11eb-841d-6e88260393a6.PNG)

**Comment by thelindat** [comment]
You need to update esx_multicharacter and possibly the dependencies.
