### ISSUE TITLE
esx menu wont show up

### ISSUE THREAD

**Issue by stxrlite** [thelindat/esx_multicharacter#18]
![image](https://user-images.githubusercontent.com/78002427/122976432-561e1580-d362-11eb-87c2-e306b17aef9e.png)

anyone know whats up with this?

**Comment by stxrlite** [comment]
yeah replaiced the menu and everything and its still not working

**Comment by thelindat** [comment]
See if the new commit helps you - it's due to slow loading times.
EDIT: The new ESX Legacy update has been merged so you need to get both.

**Comment by legendgamingusa** [comment]
Tried the new commit and still happening for me as well. If I restart esx_multicharacter it shows the menu.

**Comment by thelindat** [comment]
@legendgamingusa @xxliljaexx Can you both share your resource load order?

**Comment by PurchasedGaming** [comment]
I get this issue, this is my start order for you

ensure mysql-async
ensure ghmattimysql
ensure cron
ensure es_extended
ensure async
ensure esx_multicharacter
ensure skinchanger
ensure esx_identity
ensure esx_skin
ensure instance

**Comment by thelindat** [comment]
@PurchasedGaming You're loading multicharacter before its dependencies, which means it will load them; however you then ensure them afterwards which would mess with multicharacter.

Ensure multicharacter is loaded after identity, skin, and esx_menu_default.

**Comment by stxrlite** [comment]
> @legendgamingusa @xxliljaexx Can you both share your resource load order?

sorry life has got me busy i'll check when i get home

**Comment by stxrlite** [comment]
> @legendgamingusa @xxliljaexx Can you both share your resource load order?
i put multichar close to the bottom im going to see if it works

**Comment by stxrlite** [comment]
start async
start cron
start es_extended
start instance
start skinchanger
start esx_accessories
start esx_addonaccount
start esx_multicharacter
start esx_addoninventory
start esx_society
start gcphone
start esx_addons_gcphone
start vdk_call
start esx_policejob
start esx_ambulancejob
start esx_adminplus
start esx_bankerjob
start esx_barbershop
start esx_basicneeds
start esx_billing
start esx_boat
start esx_clotheshop
start esx_cruisecontrol
start esx_datastore
start esx_dmvschool
start esx_drugs
--start esx_garage
start esx_holdup
start esx_identity
start esx_joblisting
start esx_jobs
start esx_license
start esx_lscustom
start esx_mechanicjob
start esx_menu_default
start esx_menu_dialog
start esx_menu_list
start esx_optionalneeds
start esx_property
start esx_realestateagentjob
start chat
start esx_rpchat
start esx_service
start esx_shops
start esx_sit
start esx_skin
start esx_status
start esx_taxijob
-- start esx_voice
start esx_weaponshop
start new_banking
start trew_hud_ui
start pNotify
start esx_inventoryhud
start esx_carwash
start esx_duty
start esx_scoreboard
start esx_extraitems
start esx_doorlock
start esx_firejob
start trp_RobCashRegisters
start Lenzh_chopshop-2.0
start mythic_notify
start progressBars
start vSync
start esx_jb_trailer
-- start esx_jail
start handsup
start esx_CivAutoRepair
start esx_LiveRPregisteritems
start esx_tattoosShops
start esx_tpmenu
start esx_advancedgarage
start esx_advancedjail
start esx_licenceshop
start esx_advancedvehicleshop
start esx_plasticsurgery
start esx_inventoryhud_trunk
start esx_trunk
start mythic_progbar
start esx-kr-vehicle-push
start tgiann-mdt
start esx_pizza
start esx_poolcleaner
start esx_carlock
start esx_gardener
start esx_garbagejob
start esx_truckerjob
start esx_gopostal
start esx_dreamscratching
ensure esx_multicharacter

**Comment by thelindat** [comment]
@xxliljaexx 
You're starting dependencies for multicharacter after it, then have it added at the bottom with an ensure.

```
## These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager

## ESX Legacy
ensure mysql-async
ensure cron
ensure skinchanger
ensure es_extended
ensure esx_menu_default
ensure esx_menu_dialog
ensure esx_menu_list
ensure esx_identity
ensure esx_skin
ensure esx_multicharacter
```

**Comment by stxrlite** [comment]
> @xxliljaexx
> You're starting dependencies for multicharacter after it, then have it added at the bottom with an ensure.
> 
> ```
> ## These resources will start by default.
> ensure mapmanager
> ensure chat
> ensure spawnmanager
> ensure sessionmanager
> 
> ## ESX Legacy
> ensure mysql-async
> ensure cron
> ensure skinchanger
> ensure es_extended
> ensure esx_menu_default
> ensure esx_menu_dialog
> ensure esx_menu_list
> ensure esx_identity
> ensure esx_skin
> ensure esx_multicharacter
> ```

kay thanks i think its working now i put it under all the dpendencies

**Comment by stxrlite** [comment]
Also its still not working i relog and the menu does not appear

**Comment by stxrlite** [comment]
still not working after i put it after the dependicies

**Comment by thelindat** [comment]
> 
> 
> still not working after i put it after the dependicies

Does using the menu from [this repository](https://github.com/thelindat/esx-legacy/tree/main/%5Besx%5D/esx_menu_default) act any differently? Otherwise I'm just going to have to add a stupid amount of delay before the menu opens.

**Comment by stxrlite** [comment]
> > still not working after i put it after the dependicies
> 
> Does using the menu from [this repository](https://github.com/thelindat/esx-legacy/tree/main/%5Besx%5D/esx_menu_default) act any differently? Otherwise I'm just going to have to add a stupid amount of delay before the menu opens.

yeah i used the latest update thingy

**Comment by stxrlite** [comment]
![image](https://user-images.githubusercontent.com/78002427/123531790-86a0df00-d6d5-11eb-9917-fe253731144c.png)

**Comment by stxrlite** [comment]
its probaly not working because i was tabbed out
EDIT: it is because i was tabbed out of the game

**Comment by thelindat** [comment]
> yeah i used the latest update thingy

That link is for a consolidated repo for all base ESX resources; just try grabbing the menu (it has some changes) and see if it helps. I also just amended the last update on the multicharacter because it had a bug on spawn, so replace server/main.lua

**Comment by stxrlite** [comment]
> > yeah i used the latest update thingy
> 
> That link is for a consolidated repo for all base ESX resources; just try grabbing the menu (it has some changes) and see if it helps. I also just amended the last update on the multicharacter because it had a bug on spawn, so replace server/main.lua

will do it right now i will update you soon

**Comment by stxrlite** [comment]
> > > yeah i used the latest update thingy
> > 
> > 
> > That link is for a consolidated repo for all base ESX resources; just try grabbing the menu (it has some changes) and see if it helps. I also just amended the last update on the multicharacter because it had a bug on spawn, so replace server/main.lua
> 
> will do it right now i will update you soon

kay so now its a infinite loading black screen

**Comment by stxrlite** [comment]
> > > > yeah i used the latest update thingy
> > > 
> > > 
> > > That link is for a consolidated repo for all base ESX resources; just try grabbing the menu (it has some changes) and see if it helps. I also just amended the last update on the multicharacter because it had a bug on spawn, so replace server/main.lua
> > 
> > 
> > will do it right now i will update you soon
> 
> kay so now its a infinite loading black screen

EDIT: updated everything

**Comment by xxliljaexx** [comment]
did not mean to close it

**Comment by stxrlite** [comment]
updated to the latest versions and it worked thanks for the help

**Comment by stxrlite** [comment]
still happening

**Comment by thelindat** [comment]
Well I can't do anything else without information; there's already plenty of time for resources to be loaded.
