### ISSUE TITLE
Phone not working

### ISSUE THREAD

**Issue by InLoveWithLua** [thelindat/esx_multicharacter#20]
Hey when i use my phone and try to send sms it look like im chatting with myself. do i need to add some tables like in Kashacters?
Im using re-ignited-gcphone-esx-1-1-1-2-final
![Handy multichar](https://user-images.githubusercontent.com/75123219/123510048-9c80b680-d679-11eb-97cc-dcf26db1aeca.png)

**Comment by thelindat** [comment]
Seems rather odd but gcphone is a pretty buggy mess and I know it can have problems with multicharacter resources (in general). What are the changes for kashacters you refer to?

**Comment by InLoveWithLua** [comment]
In kashacter i addet the tables for phone_messages, phone_calls etc in server/main.lua and it worked. Maybe i need to add those to the script?

**Comment by thelindat** [comment]
Phone works fine on my end and for others, aside from the usual problems like Twitter being shared.
