### ISSUE TITLE
Black Loading screen

### ISSUE THREAD

**Issue by stxrlite** [thelindat/esx_multicharacter#25]
Hey, sorry for all the posts recently I recently switch hosters and I imported everything from my old server to new and everything's working except when I load in I get a infinite loading screen, everything was working on old hoster and everything's the same
![image](https://user-images.githubusercontent.com/78002427/125187039-918e6000-e1fb-11eb-9270-1960e96a6541.png)

**Comment by proff001** [comment]
Have you made sure you are not using any conflicting resources and that you are running the latest version of all  the required resources?

**Comment by stxrlite** [comment]
> Have you made sure you are not using any conflicting resources and that you are running the latest version of all the required resources?

Yeah

**Comment by proff001** [comment]
Any errors in F8 or in the server console?

**Comment by stxrlite** [comment]
> Any errors in F8 or in the server console?

nope everything is clean

**Comment by thelindat** [comment]
> 
> 
> Hey, sorry for all the posts recently I recently switch hosters and I imported everything from my old server to new and everything's working except when I load in I get a infinite loading screen, everything was working on old hoster and everything's the same
> ![image](https://user-images.githubusercontent.com/78002427/125187039-918e6000-e1fb-11eb-9270-1960e96a6541.png)

everything isn't working if it's not working
https://github.com/esx-framework/esx-legacy

latest files are there, make sure you're running them because it all works

**Comment by xxliljaexx** [comment]
![image](https://user-images.githubusercontent.com/78002427/125374587-53a54f00-e355-11eb-95e5-c52f3d020069.png)
cant download it :/

**Comment by stxrlite** [comment]
nvm i got it to download

**Comment by stxrlite** [comment]
so yea its still giving me a black screen after updating es_extended

**Comment by stxrlite** [comment]
i will check right now

**Comment by Imnotac0p** [comment]
This is happening to me too.  It infinaely "retrieves scripts."  It happened when I customized the  config.spawn to be at the airport.  For me at least, this seems to be the cause.  Could be a communication issue between this and spawn manager.

**Comment by Imnotac0p** [comment]
POSSIBLE SOLUTION UNTIL FIXED BY AUTHOR:  If you, like me, are getting the black screen issue after changing config.spawn,  DO NOT change the heading.  Keep it at 0.  ^_^

**Comment by SweetsMarie** [comment]
I am having the same issue. It worked perfectly a few hours ago, but now it's stuck on the black screen where multi-char should be. No errors in either console. Database has all tables updated and character length on identifier and owner are 60. I am also using the recipe Linda put on the CFX forums a few days ago. So I am confused :(

**Comment by SweetsMarie** [comment]
> I am having the same issue. It worked perfectly a few hours ago, but now it's stuck on the black screen where multi-char should be. No errors in either console. Database has all tables updated and character length on identifier and owner are 60. I am also using the recipe Linda put on the CFX forums a few days ago. So I am confused :(

Fixed, dummy me started FXServer before I started Xampp, so it wasn't reading the database. Hope my flub helps someone.

**Comment by thelindat** [comment]
This issue isn't going to get anywhere. I've got no information to go off but it seems two individuals have more-or-less the same issues that nobody can reproduce.

**Comment by mifsopo** [comment]
after changing my spawn in the database i aswell ran into this issue, i have other issues as in my open ticket, but yeah ive just ran into this issue after changing my spawn in the database
