### ISSUE TITLE
Black Screen (With server side error)

### ISSUE THREAD

**Issue by Jye-AU** [thelindat/esx_multicharacter#26]
![image](https://user-images.githubusercontent.com/24248108/126059275-7e303906-d77c-4b67-a800-424d83bbf0bb.png)
![image](https://user-images.githubusercontent.com/24248108/126059285-d5ed3e2c-d01c-4d05-ad7a-3dadc97eff29.png)
I am using your version of es_extended: https://github.com/thelindat/es_extended

**Comment by thelindat** [comment]
Download the last commit to my fork of ESX (specifically get the imports file).
