### ISSUE TITLE
infinite retrieving scrips on custom spawn point

### ISSUE THREAD

**Issue by Imnotac0p** [thelindat/esx_multicharacter#30]
I tried changing the spawn in the config to the airport (I'm assuming config.spawn controls where you spawn to create your character).  All I did was change the x,y,z,h coordinates in the line.

Now, whenever I try loading in with this setting,  I am stuck on a black screen with "retrieving scripts" infinately loading in the lower right corner.  plz halp.

**Comment by thelindat** [comment]
No information or repro.

People have been setting all sorts of spawn locations with their edits of this resource.

**Comment by mifsopo** [comment]
If you changed it i ndatabase aswell go to bottom of my issue https://github.com/thelindat/esx_multicharacter/issues/33#issuecomment-891456945
