### ISSUE TITLE
change character creation location

### ISSUE THREAD

**Issue by Imnotac0p** [thelindat/esx_multicharacter#31]
I am trying to have new characters be created at and spawn at the airport rather than the job center,  but I don't see any option to do that.

I thought it was the config.spawn, but that only seems to be for where you select your character rather than the character creator itself.  I searched all of the mod's files for any reference to this, but was unable to find it.  Anyone have any idea how to do this?

**Comment by thelindat** [comment]
Config.Spawn is the location for character selection; modify the new player spawn in your database - it's set by ESX.
