### ISSUE TITLE
Data player doesn't refresh on player selection

### ISSUE THREAD

**Issue by 0x1f0f0** [thelindat/esx_multicharacter#32]
Hello Linden, I'll report you that problem cause is very important to see the player data on the NUI and it doesn't works.
Example of the problem, look at the NUI: 
https://streamable.com/d2nzt7

**Comment by thelindat** [comment]
I know this issue existed a while back, but it was fixed.

![image](https://user-images.githubusercontent.com/65407488/127181522-e7bd5982-9eba-4b8c-a450-2016f268fdae.png)
![image](https://user-images.githubusercontent.com/65407488/127181536-81f45d34-7c9d-40a7-a080-209de1bf70c1.png)

**Comment by 0x1f0f0** [comment]
Yes, my bad, I was using the v1.2.1 - Fixed!
