### ISSUE TITLE
not loading visual

### ISSUE THREAD

**Issue by mifsopo** [thelindat/esx_multicharacter#33]
for some reason ( not only me) but the graphics dont load when choosing to pick a character 
![image](https://user-images.githubusercontent.com/44308680/127705727-d0681a92-1c6f-40d8-b455-64d2f0b7a926.png)

**Comment by thelindat** [comment]
Looks like your character is getting spawned somewhere else?

**Comment by mifsopo** [comment]
does this script handle player spawns or would it be another script interfering?

**Comment by thelindat** [comment]
It spawns you with spawnmanager, but something might be forcing a respawn or teleporting you.

**Comment by mifsopo** [comment]
hmm.. alright, ill try and see , thank you

**Comment by mifsopo** [comment]
is it possible to change the view location? say move it to southern ls?

**Comment by mifsopo** [comment]
so i just changed spawn location and the graphic issue persists, but i jsut wiped my userers data and now the menu is empty.. no optino for new character or anythihg, just blank...

**Comment by mifsopo** [comment]
so i resatarted the script while ingame made my character and it spawned me at the job center (i have changed spawn to airport) maybe i do have an interfering script?

**Comment by thelindat** [comment]
Are you running default_spawnpoint or something?

**Comment by mifsopo** [comment]
how would i tell if that? this is the first script ive installed that sets characters, im running es_extended legacy if that matters and i dont run the skater or hipster resources

**Comment by thelindat** [comment]
Post your resource start order

**Comment by mifsopo** [comment]
## These resources will start by default.
ensure mapmanager
ensure chat
ensure chat-theme-civlifechat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap

add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow

#ESX
#start essentialmode
start mysql-async
start esplugin-mysql
start es-extended
start async
start fxmigrant
ensure mysql-async
ensure cron
ensure skinchanger
ensure es_extended
ensure esx_menu_default
ensure esx_menu_dialog
ensure esx_menu_list
ensure esx_identity
ensure esx_skin
ensure esx_datastore
ensure gcphone
ensure esx_jobs
ensure esx_license
ensure esx_licenseshop
ensure esx_society
#ensure esx_accessories
ensure esx_addonaccount
ensure esx_addoninventory
ensure esx_ambulancejob
ensure esx_animations
ensure new_banking
ensure esx_bankerjob
ensure esx_barbershop
ensure esx_billing
#ensure esx_boat
#ensure esx_clotheshop
ensure esx_cruisecontrol
ensure esx_dmvschool
#ensure esx_drugs
#ensure esx_holdup
ensure mhacking
#ensure esx_joblisting
ensure esx_lscustom
ensure esx_mechanicjob
#ensure esx_kashacters
ensure esx_multicharacter
ensure esx_phone
ensure esx_policejob
ensure esx_rpchat
ensure esx_service
#ensure ESX_MultiShops
ensure esx_status
ensure esx_basicneeds
ensure esx_optionalneeds
ensure esx_taxijob
ensure esx_vehicleshop
#ensure esx_advancedvehicleshop
#ensure esx_advancedgarage
ensure esx_garage
ensure esx_voice
ensure esx_weaponshop
#ensure esx_whitelist
ensure instance
ensure esx_property
ensure esx_realestateagentjob
ensure esx_sit
ensure nui_doorlock
ensure pNotify
#ensure esx_inventoryhud
ensure inventory
ensure esx_RealisticVehicleFailure
ensure esx_radio
#ensure esx_moneywash
ensure esx_scoreboard
#ensure esx-kr-vehicle-push
#ensure PushOver
ensure mythic_notify
ensure mythic_progbar
ensure esx_shops
ensure esx_newaccessories
ensure esx_np_skinshop_v2 
ensure core_jobutilities
#ensure esx_finance
#ensure dealership


#EMS
ensure hospitalmlo
ensure Ambulancejob
ensure esx_AmbulanceGarage
ensure stretcher
ensure stretcher_props
ensure stretcher_sit

#misc
ensure gd_airport_ai_begone #removes ai spawning in airports
ensure LegacyFuel
ensure cosmo_hud
ensure trew_hud_ui
#ensure PillboxHospital
#ensure PillboxHospital-doors
#ensure Teleport
ensure bob74_ipl
ensure PiggyBack
#ensure HideInTrunk
ensure vehcontrol
ensure progressBars
ensure nfw_locksystem
ensure nfw_wep
ensure ocrp_postal_map
#ensure disc-hotwire
ensure br-menu 
ensure bt-target
ensure PolyZone
ensure thr-drugs
ensure vMenu
ensure fakeplate
ensure cc-carry
ensure online-interiors
ensure xnTattoos
ensure gabz_mrpd
#ensure danny3_outlawalert
ensure SmartTrafficLights
#ensure RealisticTraffic
#ensure RealisticDrivingV
#ensure RealisticAirControl
#ensure RealisticBrakeLights
ensure realistic_carpack
ensure rs9000
ensure lspdv
ensure lspdv2
ensure sheriffv
ensure rprogress
ensure inside-selldrugs
ensure sJewelry
ensure inside-moneywash
ensure laundry
ensure JD_logs
ensure camerasystem
ensure DOLLARWEEDESX
ensure ammo-armour
ensure kypo-drug-effect
#ensure Seatbelt
ensure taxi
ensure mdt
#ensure kypo-drug-effect
ensure utk_fleeca
ensure discord
ensure linden_outlawalert
ensure vtr_shoprobbery

**Comment by thelindat** [comment]
Get rid of `start esplugin-mysql`

You have both
```
start es-extended
ensure es_extended
```
Not sure what that's about, but if you're running different versions there will be issues.

```
add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow
```
Needs to be es_extended but that won't be causing this

**Comment by mifsopo** [comment]
the es-extended doesnt matter, the folder isnt in my resources so it just says cant be found, ive just been too lazy to take it out, but will do so, and alright ill change the others

**Comment by thelindat** [comment]
Look for any resource triggering the spawnmanager export (possibly ambulancejob)

**Comment by mifsopo** [comment]
ambulancejob/client/main.lua has this
`AddEventHandler("onClientMapStart", function()
	exports.spawnmanager:spawnPlayer()
	Citizen.Wait(5000)
	exports.spawnmanager:setAutoSpawn(false)
end)`

could that be it? idk why that would matter because its not setting a coordinate

**Comment by mifsopo** [comment]
yeah just went through all its files and thats the only instance of using that export, even then when i do spawn with ambulancejob it puts me in the hospital not where the default jobcenter is.. hmm im lost, imma see if i can use notepadd++ to search every resource file at once for 'spawnmanager'

**Comment by mifsopo** [comment]
the only place where i got hits for spawnmanager was in ambulancejob, multicharacter and es_extended in my entire resource folder

**Comment by thelindat** [comment]
Get rid of the spawnplayer export in ambulancejob.

**Comment by mifsopo** [comment]
just did that, deleted my cache and still spawns me there on new player creation, on another note, how would i raise the camera on character creation aswell as i cant see the face or hair

also the graphical issue works fine when im in the esx identity character creation 
![image](https://user-images.githubusercontent.com/44308680/127757314-ae9e8c27-0b46-4967-929b-99d06eca2220.png)

**Comment by mifsopo** [comment]
this is my entire resource folder 
![image](https://user-images.githubusercontent.com/44308680/127758409-4a47f966-8083-4451-8fc7-fbe7dffa170a.png)
i already removed ambulancejob spawnmanagers
this is where its mentioned in es_extended 
![image](https://user-images.githubusercontent.com/44308680/127758504-ffa60426-80fc-4852-aaea-d1c5ebe24b79.png)

**Comment by mifsopo** [comment]
one final fix i am trying but if you could help, im trying to reinstall all dependencys with e required verion, mysql-async im on 3.3.2
es_extedned im on legacy but the github for identity and skin is hidden right now, so i cant tell 100% if im on the right versions of those , do you have the required identity and skin you can send me? that might be the issue?

**Comment by mifsopo** [comment]
i no longer seem to have graphical issue except where i changed my spawn in the database, its constant blackscreen and stuck loading. i cant revert to original spawn because i cant undo changes in database and im now stuck on my server permanatley until i can get the original spawn coord which im not sure what they are as i cant access esx_identity and skin due to them being removed from github

**Comment by mifsopo** [comment]
well. now i have a wonderful problem, i got the default spawn from using the sql in the es_extended that was in the legacy es_extended and now after restarting my server and making a new character im still in a black screen and now i get this error 
![image](https://user-images.githubusercontent.com/44308680/127782155-92b0cb0e-623f-46fc-86fd-02e2adcb89f0.png)
i dont know whats going on, but ive just ran into problem after problem with this script i have no clue why because now i should have EVERYTHING you have as a dependancy and im just getting more errors.

**Comment by mifsopo** [comment]
![image](https://user-images.githubusercontent.com/44308680/127782378-83907f8a-2259-4426-83dd-97a1f3a4aad2.png)

**Comment by mifsopo** [comment]
and im once again back to graphical issues just by relogging. i dont know what is going on but i cant even reset this stuff and get it working, i should have just left it with shitty graphical issues and job center spawning 
![image](https://user-images.githubusercontent.com/44308680/127782640-03f91a62-f55b-42ec-9e7c-3e07173e97bf.png)
now no one can join and test my server because this resource is so screwy . ive done everything, ive reinstalled multichar. set my database name. re installed identity. skin both from the es_extended legacy repository. ive got version 3.3.2 of mysql-async everything ive dont according to the instructions and its giving me more problems now than before 

if i restart esx_multicharacter while on the choose a character menu it goes to working 
![image](https://user-images.githubusercontent.com/44308680/127782706-2f149a27-b264-42d9-b1bb-c123255c4a24.png)
except then the create new character optino stops working
and i get a list of errors 
![image](https://user-images.githubusercontent.com/44308680/127782727-487dd547-1fe5-404f-933a-364ed0de8e9a.png)

**Comment by mifsopo** [comment]
just reinstalled everything once again.  my database coords are {“heading”:0.0,“z”:71.1,“y”:19.3,“x”:-1.5}

SO i just now decided to reinstall es_extended legacy even and it STILL is not working.. so ive reinstalled every single script now and its givning me the same exact error so unless es_legacy repository is bad bc thats where i got esx_skin and esx_identity i have no clue. because the identity and skin links you have posted are bad links. 
![image](https://user-images.githubusercontent.com/44308680/127785003-f67b9263-eb32-4723-9bb9-ca7db54805e8.png)

![image](https://user-images.githubusercontent.com/44308680/127785043-77732d76-381a-4541-9509-c23967227452.png)


the position is '{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}'


even deleting my cache fixes the graphical issues but still loads into black screen with continuous loading bar at bottom right
![image](https://user-images.githubusercontent.com/44308680/127785262-1765c8f1-1d27-473f-b700-de1dd6818936.png)

**Comment by thelindat** [comment]
If `spawn` is nil, then the coordinates for the selected character are NULL in the database. Same cause for nil `coords` in es_extended.


Having a blackscreen and stuck loading happens if you are not spawning in at all. Ensure you do not have en edited spawnmanager (I know a lot of servers that were using 1.1 edited it, for various reasons).
https://github.com/citizenfx/cfx-server-data/blob/master/resources/%5Bmanagers%5D/spawnmanager/spawnmanager.lua


The graphical issues are caused by the camera being set at a location that is far away from where your ped is standing. Restarting the resource while active causes your ped to respawn, thus solving the graphical issues, however it breaks esx_menu_default because it suddenly gets forced to reload.



This is not a general issue that people have, so something on your server is doing something; however I will apply some fixes in an attempt to resolve the problem.
- Forcibly respawn the ped if they aren't near the character selection area
- Set fallback spawn coordinates if the player does not have any
- Force esx_menu_default to close all UIs when the resource is restarted

**Comment by mifsopo** [comment]
Ive already reinstalled the default spawnmanager so unless its one of the fixes you mentioned above, ill have to research how to do some of those options because ive never done anything like that, but ill post an uodate when i get off work

**Comment by mifsopo** [comment]
ok so i just stopped every script except for the required scripts including es_extended and i still have the nil coords error.. can you sent me a database coordinate that i ened? maybe the coordinate is a problem in my database...

HOLY FUCK idk why this is was the problem. for some reason editing the coords in the database really screwed stuff up, i just did deleted my positions table and added this 

`USE `es_extended`;

ALTER TABLE `users`
	ADD COLUMN `position` VARCHAR(255) NULL DEFAULT '{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}'
;
`

and now it works.. idk what the actual problem was even tho i copied the insert.. but for some reason this time it worked, id just suggest that for the future fixes, delete your positions table and add the above back to your databa se


OKAY after further investigation the problem was happening when i COPIED and PASTED coordinates, for some reason even if there was no slash (/) when i hit enter it added the slash  i dont know why but im assuming that was the problem 

![image](https://user-images.githubusercontent.com/44308680/127947012-5c390af2-9a65-4d82-ae68-6364c18e57a6.png)

notice the slash above and how its missing now
