### ISSUE TITLE
Stuck 

### ISSUE THREAD

**Issue by cjosephdc** [thelindat/esx_multicharacter#34]
Im stuck right after clicking PLAY WITH CHAR. Creating new char is ok. 
Got this error after the latest commit

**Comment by thelindat** [comment]
Need an error message.

**Comment by levi9956** [comment]
i have the same issue but theres no error message. im fine but all my friends get stuck after selecting character like this.

![image](https://user-images.githubusercontent.com/81165457/127747438-98bbbd69-0017-484e-b1a2-5ebf43889972.png)

**Comment by thelindat** [comment]
All characters, new characters, old characters?

In server main, find
```lua
	RegisterServerEvent("esx_multicharacter:CharacterChosen")
	AddEventHandler('esx_multicharacter:CharacterChosen', function(charid, isNew)
		local src = source
		if type(charid) == 'number' and string.len(charid) <= 2 and type(isNew) == 'boolean' then
			if isNew then
				awaitingRegistration[src] = charid
			else
				TriggerEvent('esx:onPlayerJoined', src, Config.Prefix..charid)
			end
		end
	end)
```
and replace with
```lua
	RegisterServerEvent("esx_multicharacter:CharacterChosen")
	AddEventHandler('esx_multicharacter:CharacterChosen', function(charid, isNew)
	print(source, charid, isNew)
	print(type(charid), string.len(charid), type(isNew))
		local src = source
		if type(charid) == 'number' and string.len(charid) <= 2 and type(isNew) == 'boolean' then
			if isNew then
				awaitingRegistration[src] = charid
			else
				print('trigger onPlayerJoined')
				TriggerEvent('esx:onPlayerJoined', src, Config.Prefix..charid)
			end
		end
	end)
```


This is not a fix, but I need the results of the print messages from server console.

**Comment by cjosephdc** [comment]
![image](https://user-images.githubusercontent.com/87730839/127863624-e1785208-992c-4e0f-b9da-960b51954416.png)

**Comment by cjosephdc** [comment]
the issue is only on old characters.

**Comment by thelindat** [comment]
```lua
if Config.Multichar then
	AddEventHandler('esx:onPlayerJoined', function(src, char, data)
		if not ESX.Players[src] then
			local identifier = char..':'..ESX.GetIdentifier(src)
			if data then
				createESXPlayer(identifier, src, data)
			else
				loadESXPlayer(identifier, src, false)
			end
```
replace with
```lua
if Config.Multichar then
	AddEventHandler('esx:onPlayerJoined', function(src, char, data)
	print(src, char, json.encode(data))
		if not ESX.Players[src] then
			local identifier = char..':'..ESX.GetIdentifier(src)
			print(identifier)
			if data then
			print('createplayer')
				createESXPlayer(identifier, src, data)
			else
			print('loadplayer')
				loadESXPlayer(identifier, src, false)
			end
```

**Comment by cjosephdc** [comment]
There's a NULL value on the print.

![image](https://user-images.githubusercontent.com/87730839/128002079-69bf9f04-40d6-4988-891a-da986e6e37c3.png)

**Comment by thelindat** [comment]
Based on that, everything is loading fine. The player character gets created and the load events are working.
https://github.com/thelindat/esx_multicharacter/blob/master/client/main.lua#L262

That is the event triggered after xPlayer creation. All I can suggest is throwing print values throughout the event until you find where it's getting stuck.

**Comment by CasualLeopard37** [comment]
having the same issue, any fix?

**Comment by thelindat** [comment]
No repro, no info, no response.
