### ISSUE TITLE
black screen with spinning wheel.

### ISSUE THREAD

**Issue by ElusionPDX** [thelindat/esx_multicharacter#4]
I have updated everything that you have listed on the git page for it. Have the command added as well. 
If i restart the resource that has the command in it then the black screen goes away. 

![image](https://user-images.githubusercontent.com/19332765/120896112-0fa08b00-c5ee-11eb-8077-721badd965dc.png)

**Comment by thelindat** [comment]
Did you run the command from console?

Include any error or warning messages (client and server), as well as your resource list from server.cfg

**Comment by ElusionPDX** [comment]
When I run the command from console this error pops
I added the command to a random resource. does it matter what resource i added the command to.
[       script:zs-mdt] SCRIPT ERROR: @zs-mdt/sv_mdt.lua:644: bad argument #1 to 'pairs' (table expected, got nil)
[       script:zs-mdt] > ref (@zs-mdt/sv_mdt.lua:644)

![image](https://user-images.githubusercontent.com/19332765/120900197-7b402380-c601-11eb-8288-bd4eef16c679.png)

**Comment by ElusionPDX** [comment]
Also only shows chars that are made with this system and not the other ones that we made with kash.

**Comment by thelindat** [comment]
> I added the command to a random resource. does it matter what resource i added the command to.  

You need to add the command to the multichararacter. Use it once, then remove when done. It can't get triggered by anybody, but there's no need to have it registered.

> [ script:zs-mdt] SCRIPT ERROR: @zs-mdt/sv_mdt.lua:644: bad argument #1 to 'pairs' (table expected, got nil)  

![image](https://user-images.githubusercontent.com/65407488/120902696-162e1180-c685-11eb-8474-feeade967d08.png)
If you have not done that (maybe you did, but you're using the command from a random resource)

> Also only shows chars that are made with this system and not the other ones that we made with kash.  

While this resource is a fork, as stated in the readme characters are stored as `char#:license`. kashacters stores your last played character as the raw identifier and will modify every table when swapping.

If you are on a live server and wish to swap, you will need to wait for a conversion method (I am focused on other tasks right now).

**Comment by ElusionPDX** [comment]
I have added it to the multi char script and it gives the same error of nil when i run it from console.

DB is set in the server/main.lua
	-- enter the name of your database here
	Config.Database = 'rexl'
	-- enter a prefix to prepend to all user identifiers (keep it short)
	Config.Prefix = 'Char'


I have the prefix set in the config as how all other accounts are stored. Pre
Char(slot#):gta_license 

All the chars in the system are stored as Char1:gta_license, Char2:gta_license, Char3:gta_license so i though it would work. All well it was a hope.

**Comment by ElusionPDX** [comment]
Ok so got it to run the command by moving the it out side to its own thing

Also got all my old chars to load, yay for me. Issue is still the black screen. 

> ESX = exports['es_extended']:getSharedObject()
> 	local IdentifierTables = {}
> if ESX.GetConfig().Multichar == true then
> 	local fetchCharacters = -1



![image](https://user-images.githubusercontent.com/19332765/120905580-fcf37980-c620-11eb-8e7a-220583615817.png)

**Comment by thelindat** [comment]
> Include any error or warning messages (client and server), as well as your resource list from server.cfg

I can't resolve your issue without any information. Also, I see you have my inventory - are you using my Legacy fork or edits?

**Comment by Hikato** [comment]
Have you updated esx_identity?

**Comment by ElusionPDX** [comment]
everything is running off the copys linked in the post for multi char. 

its working now after redownloading it. so maybe it was just a bum zip download from git.
