### ISSUE TITLE
esx_multicharacter doesn't delete characters

### ISSUE THREAD

**Issue by Chrimsonflame14** [thelindat/esx_multicharacter#47]
Hello, I'm having an issue with deleting characters. When me or any other member try to delete characters it just sits on the character that we are trying to delete with information about character but no selection HUD.

**Comment by CarlBishop** [comment]
you didn't inserted the name of your db in the server file

**Comment by thelindat** [comment]
As above, you need to enter your database name. Might fix it up in the future to retrieve it from connection string, but for now it is what is is.
