### ISSUE TITLE
fivem-appearance/esx_multicharacter incompatibility 

### ISSUE THREAD

**Issue by StuxxyOfficial** [thelindat/esx_multicharacter#48]
the following commit seems to break the compatibility between this resource and fivem-appearance. before i reverted the code, after character creation, the user would get stuck and not teleport to the spawn location. 

https://github.com/thelindat/esx_multicharacter/commit/d412efab05d416cdf1020f5d8a456622ba3e7fd2

**Comment by thelindat** [comment]
The previous code didn't function properly - not sure how concealing other players and changing a wait time is breaking your resource?
