### ISSUE TITLE
Deleted Last Only One character may make next login glitched.

### ISSUE THREAD

**Issue by negbook** [thelindat/esx_multicharacter#5]
Lost Login and Lost Skin selection after deleted last only one character.And database still having that char1.
	Config.Database is correct.

**Comment by thelindat** [comment]
Unable to reproduce.
Deleting my one and only character results in identity being displayed - spawning then shows esx_skin.
Same result when deleting multiple characters.

No characters remain in the database after being deleted, as expected.


Please share any errors or warnings, and ensure you are running the latest skin and identity.

**Comment by negbook** [comment]
OOPS.I forgot to add esx_skin into resources.cfg
