### ISSUE TITLE
can't move and wont teleport to spawn after creating/saving character.

### ISSUE THREAD

**Issue by CucoMonster** [thelindat/esx_multicharacter#51]
Hi. I am using FiveM-Appearance and the menu shows up fine when creating character, however once I save the character after creating it, the camera changes angle but it doesnt teleport me to the new spawn location or anything. I am also unable to move my character. 

Here is a video of it in action and below is a screenshot of me being stuck.

[Video Stuck After Creating Character](https://medal.tv/clips/4wbWcz7g9r7BC/IvHd3C6y4ezN)

[Screenshot](https://cdn.discordapp.com/attachments/490315679862358019/894156518482644992/unknown.png)

sidenote: Currently i dont have esx_skin activated BUT If I have both fivem-appearance and esx_skin activated I get both menus. Once I finish making my character with fivem-appearance I then am able to click the esx_skin menu and if I hit enter it does teleport me like it should. -- If I use only esx_skin and not fivem-apperance, the script works great. but it doesn't if its the other way around (if that makes sense).

If there is no fix for this, is there a way I can turn off fivem-appearance when creating a new character and only have esx_skin? but still have fivem-appearance at stores/barbershops? Cause I would be willing to do that if it makes esx_multicharacter work for me.

**Comment by thelindat** [comment]
https://github.com/thelindat/brp-fivem-appearance/tree/patch-1

Somebody made a breaking commit for multicharacter support; you can get the patch to resolve it (untested, but no reason it shouldn't work).

**Comment by CucoMonster** [comment]
Sadly, it's still happening. I tried it with a freshly installed esx_multicharacter and the patched fivem-appearance you linked. Still get the same problem where I can't move the camera or the character and only see the back of my character. -- I also have an issue where I can't delete a character even after confirming that I want to delete, it just stays there with no menus open and I have to restart fivem to exit the screen (and the character would still be there when I come back).

**Comment by StuxxyOfficial** [comment]
You need to edit your database name in  esx_character/server/main.lua

Not sure if that will solve your initial issue but will resolve the deleting character issues.

**Comment by CucoMonster** [comment]
> You need to edit your database name in esx_character/server/main.lua
> 
> Not sure if that will solve your initial issue but will resolve the deleting character issues.

Thank you. I had a fresh install and forgot about this. This did help with my deleting a character problem.

As far as my original problem. It's still happening after the database change. Not sure what could be causing this. 

For now I made it so that once you register a character you just spawn in instead of editing/creating your character and then can go into a shop to change your appearance until a solution for this comes. Thanks so much for creating esx_multicharacter. It's an amazing resource,

**Comment by StuxxyOfficial** [comment]
Try with the latest commits, might of fixed the issue.

**Comment by StuxxyOfficial** [comment]
> > You need to edit your database name in esx_character/server/main.lua
> > Not sure if that will solve your initial issue but will resolve the deleting character issues.
> 
> Thank you. I had a fresh install and forgot about this. This did help with my deleting a character problem.
> 
> As far as my original problem. It's still happening after the database change. Not sure what could be causing this.
> 
> For now I made it so that once you register a character you just spawn in instead of editing/creating your character and then can go into a shop to change your appearance until a solution for this comes. Thanks so much for creating esx_multicharacter. It's an amazing resource,

Try with the latest commits, might of fixed the issue.

**Comment by thelindat** [comment]
> For now I made it so that once you register a character you just spawn in instead of editing/creating your character and then can go into a shop to change your appearance until a solution for this comes. Thanks so much for creating esx_multicharacter. It's an amazing resource,

https://github.com/thelindat/brp-fivem-appearance/tree/patch-2

Didn't test my patch and assumed it would be fine; this one does indeed work though. New updates to multichar also make things a bit easier by parsing your database.

**Comment by thelindat** [comment]
> For now I made it so that once you register a character you just spawn in instead of editing/creating your character and then can go into a shop to change your appearance until a solution for this comes. Thanks so much for creating esx_multicharacter. It's an amazing resource,

https://github.com/thelindat/brp-fivem-appearance/tree/patch-2

Didn't test my patch and assumed it would be fine; this one does indeed work though. New updates to multichar also make things a bit easier by parsing your database.

**Comment by CucoMonster** [comment]
> > For now I made it so that once you register a character you just spawn in instead of editing/creating your character and then can go into a shop to change your appearance until a solution for this comes. Thanks so much for creating esx_multicharacter. It's an amazing resource,
> 
> https://github.com/thelindat/brp-fivem-appearance/tree/patch-2
> 
> Didn't test my patch and assumed it would be fine; this one does indeed work though. New updates to multichar also make things a bit easier by parsing your database.

Awesome, thank you. This does indeed fix the issue! Thanks for your hard work!
