### ISSUE TITLE
Creating character issue

### ISSUE THREAD

**Issue by VojtaNN** [thelindat/esx_multicharacter#52]
When I click on “buy a ticket” after filling in the data, the table for creating a character will turn itself off. And i can’t move.
NO F8 ERRORS OR CONSOLE ERRORS
[VIDEO](https://files.fm/f/4ybt8w55p)

**Comment by 2Girls1CJ** [comment]
also having this problem

**Comment by 2Girls1CJ** [comment]
i found out it was a certain resource doing this, in may case it was MF_doors but still cant figure out why that script causes it

**Comment by thelindat** [comment]
Somehow MF doors does something that messes with spawning, but there's 0 I can do about it. I have no information, and I definitely don't have access to their code.

**Comment by TlYPN** [comment]
unfortunately it isnt soley doors, as i have this same issue in my city. i use MF inventory, and DrugFX

**Comment by thelindat** [comment]
Afaik MF don't even officially support Legacy and it seems every one of my resources, designed for Legacy, ends up having some sort of issue.

**Comment by TlYPN** [comment]
Well i feel like your resources do as intended, and the other developers who dont like to edit framworks, to match there needs are the ones to blame.

**Comment by Copenhagen-Gaming** [comment]
i also have the same issue, i use mf_doors also but figured out its linked to mhacking, if i remove both of them resources than it works fine

**Comment by thelindat** [comment]
@Copenhagen-Gaming
@2Girls1CJ

Is this still an issue? Somebody reported it was working fine since recent changes (not sure why 😕)
