### ISSUE TITLE
Is there going to be a version for oxmysql?

### ISSUE THREAD

**Issue by tony-stark-17** [thelindat/esx_multicharacter#53]

**Comment by thelindat** [comment]
You should be able to just swap `@mysql-async` in the fxmanifest with `@oxmysql` without any issues, using the new-ish library import.

**Comment by tony-stark-17** [comment]
> You should be able to just swap `@mysql-async` in the fxmanifest with `@oxmysql` without any issues, using the new-ish library import.

I am using the 1.5.1 and I am having issues.

**Comment by tony-stark-17** [comment]
`[      script:oxmysql] [ERROR] esx_multicharacter was unable to execute a query!
[      script:oxmysql]         Undefined array parameter #3
[      script:oxmysql]         SELECT `slots` FROM `multicharacter_slots` WHERE identifier = ? ["439314e657622e6be32584dd2f6c100f69e0f246",1]`

**Comment by thelindat** [comment]
This was an issue caused by Ox ESX that has been resolved (otherwise return value shouldn't contain the 1).
