### ISSUE TITLE
Bug, not sure how to fix exactly.

### ISSUE THREAD

**Issue by Suliure** [thelindat/esx_multicharacter#60]
![image](https://user-images.githubusercontent.com/81801406/141742610-3d958095-25aa-45f0-937f-ff443ea9aa53.png)

**Comment by thelindat** [comment]
You don't have an accounts column in your users table (it's part of ESX itself, so going to guess _outdated version_).

**Comment by therealnoskill** [comment]
i have the problem when i connect the picture stucked sometimes. so i cant do anymore

![image](https://user-images.githubusercontent.com/35240334/142178043-0f0215dc-3654-4d9a-9e8f-69638303aef0.png)

maybe can anyone help me to fix that?

when i create a char after that this happen when i have reconnect

**Comment by therealnoskill** [comment]
after i reconnect and choose the character ive created i can set my clothing. butr why stuck on first create a char ?
