### ISSUE TITLE
picking character issue

### ISSUE THREAD

**Issue by SmokyDrft** [thelindat/esx_multicharacter#61]
After a new player loads into the server, they cannot see the options to create a new character, its just a blank screen looking out into los santos, tried reinstalling it and everything, a few people can create a character and after that it breaks

**Comment by SmokyDrft** [comment]
Update.... players who already have a character, cant see there character when selecting, and the world behind them looks like a potato, not loaded in. Any help would be awesome

**Comment by thelindat** [comment]
Suffice to say that this isn't something I can reproduce, or has been reported by anyone else.

**Comment by AnthoHansen** [comment]
@SmokyDrft Checked out the dependencies and the script that are not compatible with multicharacter? 
It can be the basic-gamemode for example, if you have another script to spawn the players the world won't load around the player with multichar...

Give more info... player or server console screenshots that shows the errors... a video... something to can check it out and help you, without info it's imposible to replicate and to help you.

Have a nice day!
