### ISSUE TITLE
Unusual Resource Manager Activity

### ISSUE THREAD

**Issue by meltynetv2** [thelindat/esx_multicharacter#64]
Hello! So recently I have been noticing some unusual activity from the esx_multicharacter showing up every few seconds consistently in resource manager after player spawn. Id say every 2-3 seconds it pops to the top.
<img width="805" alt="a1f98c04ef14ad7a21df3b1c45311f58" src="https://user-images.githubusercontent.com/80143520/147161637-0e7fc141-a49c-44da-849d-4ac903e560d5.png">

I am using the latest version which is 1.4.2. I am not sure if this is a bug with FiveM itself or what, but it is only this resource doing it and I've tried removing lines and everything and it doesn't stop popping up in resource manager. If I restart the multicharacter resource it goes away, but only when your already spawned in. Which helps nothing and pinpoints nothing.

As well went through every loop/while statement and event trigger and added a `print` to them to possibly find what part is triggering it, but no prints pop up in console or anything, its like nothing is being triggered, but it still pops to the top in resource manager. Weirder thing is when it pops to the top my overall CPU msec doesn't increase, which it should if multicharacter is in the 0.30s... so weird...

Anyways like I said not sure what is causing it, maybe something on my end or FiveMs end, but maybe someone can shed some light or have a fix for this? Or maybe a way to diagnose this even further? Is this happening for anyone else or just me? Thanks for any help anyone can give to solve this bug.

**Comment by thelindat** [comment]
It's a visual bug in FiveM, since the change to the Lua runtime for "tickless resources".
See https://github.com/citizenfx/fivem/issues/1171

**Comment by meltynetv2** [comment]
> It's a visual bug in FiveM, since the change to the Lua runtime for "tickless resources". See [citizenfx/fivem#1171](https://github.com/citizenfx/fivem/issues/1171)

Thank you, that is exactly what I figured! Appreciate the help!
