### ISSUE TITLE
Invisible character on load

### ISSUE THREAD

**Issue by MJRamon** [thelindat/esx_multicharacter#71]
Enter the server, wait for loading. First loaded character will be transparent, but you can hear him moving. Move down in the list, move up - he becomes visible.

**Comment by MJRamon** [comment]
Though if I change this line 
```
if spawned == false then SetupCharacter(Character) end
```
https://github.com/thelindat/esx_multicharacter/blob/02352a8e18176cb9f369ba608aab66ccf0311fe0/client/main.lua#L178

to
```
if spawned == false then
	SetupCharacter(Character)

	Citizen.Wait(100)
	SetupCharacter(Character)
	SetPedAoBlobRendering(PlayerPedId(), true)
	ResetEntityAlpha(PlayerPedId())
end
```
(yes, with double SetupCharacter()), then character becomes visible.

**Comment by thelindat** [comment]
just sounds like basic-gamemode to me

**Comment by MJRamon** [comment]
basic-gamemode isn't loaded. Server works on ESX Legacy.

**Comment by thelindat** [comment]
Then fuck knows what you're doing, because this is designed for ESX Legacy and works fine with a basic install.

**Comment by MJRamon** [comment]
Yeah, a fucking mystery
